import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class RimaLocaleController {
  RimaLocaleController._();

  static final ValueNotifier<String> language = ValueNotifier<String>('en');

  static String get code => language.value;
  static bool get isArabic => code == 'ar';
  static TextDirection get textDirection =>
      isArabic ? TextDirection.rtl : TextDirection.ltr;

  static Future<void> loadFromProfile() async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return;

    try {
      final profile = await Supabase.instance.client
          .from('profiles')
          .select('preferred_language')
          .eq('id', user.id)
          .maybeSingle();

      final saved =
          profile?['preferred_language']?.toString().toLowerCase();

      if (saved == 'ar' || saved == 'fr' || saved == 'en') {
        language.value = saved!;
      }
    } catch (e) {
      debugPrint('RIMA LANGUAGE LOAD ERROR: $e');
    }
  }

  static Future<void> changeLanguage(String code) async {
    if (code != 'ar' && code != 'fr' && code != 'en') return;

    final user = Supabase.instance.client.auth.currentUser;
    if (user != null) {
      await Supabase.instance.client
          .from('profiles')
          .update({'preferred_language': code})
          .eq('id', user.id);
    }

    language.value = code;
  }
}

class RimaText {
  RimaText._();

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'welcome': 'Welcome to RIMA 👋',
      'tagline': 'Move smarter. Ride easier.',
      'destination': 'Where are you going?',
      'services': 'Services',
      'goSubtitle': 'Your everyday ride',
      'foodSubtitle': 'Food delivered to you',
      'expressSubtitle': 'Send anything, anywhere',
      'paySubtitle': 'Pay. Save. Simplify.',
      'bookRide': 'BOOK A RIDE',
      'comingSoon': 'COMING SOON',
      'viewWallet': 'VIEW WALLET',
      'quickAccess': 'Quick access',
      'recentActivity': 'Recent activity',
      'seeTrips': 'See your trips',
      'home': 'Home',
      'activity': 'Activity',
      'wallet': 'Wallet',
      'messages': 'Messages',
      'profile': 'Profile',
      'language': 'Language',
      'chooseLanguage': 'Choose your language',
      'english': 'English',
      'french': 'Français',
      'arabic': 'العربية',
    },
    'fr': {
      'welcome': 'Bienvenue chez RIMA 👋',
      'tagline': 'Déplacez-vous mieux. Voyagez facilement.',
      'destination': 'Où allez-vous ?',
      'services': 'Nos services',
      'goSubtitle': 'Votre trajet au quotidien',
      'foodSubtitle': 'Vos repas livrés chez vous',
      'expressSubtitle': 'Envoyez partout, facilement',
      'paySubtitle': 'Payez. Économisez. Simplifiez.',
      'bookRide': 'RÉSERVER',
      'comingSoon': 'BIENTÔT',
      'viewWallet': 'PORTEFEUILLE',
      'quickAccess': 'Accès rapide',
      'recentActivity': 'Activité récente',
      'seeTrips': 'Voir vos trajets',
      'home': 'Accueil',
      'activity': 'Activité',
      'wallet': 'Portefeuille',
      'messages': 'Messages',
      'profile': 'Profil',
      'language': 'Langue',
      'chooseLanguage': 'Choisissez votre langue',
      'english': 'English',
      'french': 'Français',
      'arabic': 'العربية',
    },
    'ar': {
      'welcome': 'مرحبًا بك في RIMA 👋',
      'tagline': 'تنقّل بذكاء. واركب بسهولة.',
      'destination': 'إلى أين تريد الذهاب؟',
      'services': 'الخدمات',
      'goSubtitle': 'رحلتك اليومية',
      'foodSubtitle': 'طعامك يصلك إليك',
      'expressSubtitle': 'أرسل أي شيء إلى أي مكان',
      'paySubtitle': 'ادفع. وفّر. ببساطة.',
      'bookRide': 'احجز رحلة',
      'comingSoon': 'قريبًا',
      'viewWallet': 'عرض المحفظة',
      'quickAccess': 'الوصول السريع',
      'recentActivity': 'النشاط الأخير',
      'seeTrips': 'عرض رحلاتك',
      'home': 'الرئيسية',
      'activity': 'النشاط',
      'wallet': 'المحفظة',
      'messages': 'الرسائل',
      'profile': 'الملف الشخصي',
      'language': 'اللغة',
      'chooseLanguage': 'اختر لغتك',
      'english': 'English',
      'french': 'Français',
      'arabic': 'العربية',
    },
  };

  static const Map<String, String> _fr = {
    'RIMA customer': 'Client RIMA',
    'Profile': 'Profil',
    'Personal information': 'Informations personnelles',
    'Saved places': 'Lieux enregistrés',
    'Language': 'Langue',
    'Notifications': 'Notifications',
    'Help & support': 'Aide et assistance',
    'Logout': 'Se déconnecter',
    'Log out': 'Se déconnecter',
    'Log out?': 'Se déconnecter ?',
    'Are you sure you want to log out?': 'Voulez-vous vraiment vous déconnecter ?',
    'Cancel': 'Annuler',
    'Personal information updated.': 'Informations personnelles mises à jour.',
    'First name': 'Prénom',
    'Last name': 'Nom',
    'Email': 'E-mail',
    'Saving...': 'Enregistrement...',
    'Save changes': 'Enregistrer les modifications',
    'No saved places yet': 'Aucun lieu enregistré',
    'Places saved during booking will appear here.': 'Les lieux enregistrés pendant une réservation apparaîtront ici.',
    'Saved place': 'Lieu enregistré',
    'Location': 'Emplacement',
    'Push notifications': 'Notifications push',
    'Ride updates, driver arrival and important RIMA alerts': 'Mises à jour des trajets, arrivée du chauffeur et alertes importantes de RIMA',
    'Your support request was sent.': 'Votre demande d’assistance a été envoyée.',
    'Unable to send support request.': 'Impossible d’envoyer la demande d’assistance.',
    'How can we help?': 'Comment pouvons-nous vous aider ?',
    'Send a message to the RIMA support team.': 'Envoyez un message à l’équipe d’assistance RIMA.',
    'Subject': 'Objet',
    'Sending...': 'Envoi...',
    'Send to support': 'Envoyer à l’assistance',
    'Use current location': 'Utiliser votre position actuelle',
    'Getting your location...': 'Recherche de votre position...',
    'Location services are disabled': 'Les services de localisation sont désactivés',
    'Location permission denied': 'Autorisation de localisation refusée',
    'Location permission permanently denied': 'Autorisation de localisation refusée définitivement',
    'Your current location': 'Votre position actuelle',
    'Unable to get location': 'Impossible d’obtenir votre position',
    'Pickup confirmed': 'Point de départ confirmé',
    'Pickup location confirmed': 'Point de départ confirmé',
    'Where would you like to go?': 'Où souhaitez-vous aller ?',
    'Choose your pickup and destination.': 'Choisissez votre point de départ et votre destination.',
    'Pickup': 'Départ',
    'Destination': 'Destination',
    'Where are you going?': 'Où allez-vous ?',
    'Your pickup': 'Votre point de départ',
    'Move the map to fine-tune your pickup point.': 'Déplacez la carte pour préciser votre point de départ.',
    'Pickup changed': 'Point de départ modifié',
    'Confirm pickup': 'Confirmer le départ',
    'Quick locations': 'Lieux rapides',
    'Home': 'Domicile',
    'Work': 'Travail',
    'Saved': 'Enregistrés',
    'Pickup help': 'Aide pour le départ',
    'Use GPS, move the pin, or choose a nearby landmark.': 'Utilisez le GPS, déplacez le repère ou choisissez un point de repère proche.',
    'Choose destination': 'Choisir la destination',
    'Move map to adjust pickup': 'Déplacez la carte pour ajuster le départ',
    'Ride history': 'Historique des trajets',
    'Retry': 'Réessayer',
    'No ride history yet': 'Aucun trajet pour le moment',
    'Completed and cancelled rides will appear here.': 'Les trajets terminés et annulés apparaîtront ici.',
    'Unknown date': 'Date inconnue',
    'Completed': 'Terminé',
    'Cancelled': 'Annulé',
    'Ride receipt': 'Reçu du trajet',
    'Ride completed': 'Trajet terminé',
    'Ride cancelled': 'Trajet annulé',
    'Trip': 'Trajet',
    'Ride ID': 'ID du trajet',
    'Date': 'Date',
    'Distance': 'Distance',
    'Duration': 'Durée',
    'Driver': 'Chauffeur',
    'Customer': 'Client',
    'Vehicle': 'Véhicule',
    'Plate': 'Plaque',
    'Your rating': 'Votre note',
    'Rating': 'Note',
    'Comment': 'Commentaire',
    'Payment': 'Paiement',
    'Status': 'Statut',
    'Method': 'Méthode',
    'Amount': 'Montant',
    'Transaction': 'Transaction',
    'Paid': 'Payé',
    'Not configured': 'Non configuré',
    'Not started': 'Non commencé',
    'Pending': 'En attente',
    'Authorized': 'Autorisé',
    'Processing': 'Traitement en cours',
    'Failed': 'Échec',
    'Refunded': 'Remboursé',
    'Finding your driver': 'Recherche de votre chauffeur',
    'Driver found': 'Chauffeur trouvé',
    'Payment required': 'Paiement requis',
    'Payment confirmed': 'Paiement confirmé',
    'Driver on the way': 'Chauffeur en route',
    'Driver has arrived': 'Votre chauffeur est arrivé',
    'Ride in progress': 'Trajet en cours',
    'Searching for available RIMA drivers nearby.': 'Recherche de chauffeurs RIMA disponibles à proximité.',
    'A RIMA driver accepted your ride.': 'Un chauffeur RIMA a accepté votre trajet.',
    'Your driver accepted the ride. Complete payment to confirm your trip.': 'Votre chauffeur a accepté le trajet. Effectuez le paiement pour confirmer.',
    'Your payment is confirmed. Your driver can now head to your pickup location.': 'Votre paiement est confirmé. Votre chauffeur peut maintenant se rendre au point de départ.',
    'Your driver is heading to your pickup location.': 'Votre chauffeur se dirige vers votre point de départ.',
    'Your driver is waiting at your pickup location.': 'Votre chauffeur vous attend au point de départ.',
    'You are on your way to your destination.': 'Vous êtes en route vers votre destination.',
    'Thank you for riding with RIMA. Please rate your driver.': 'Merci d’avoir choisi RIMA. Veuillez noter votre chauffeur.',
    'This ride has been cancelled. Returning home...': 'Ce trajet a été annulé. Retour à l’accueil...',
    'Checking your ride status...': 'Vérification de l’état de votre trajet...',
    'Cancel ride?': 'Annuler le trajet ?',
    'Are you sure you want to cancel this RIMA ride?': 'Voulez-vous vraiment annuler ce trajet RIMA ?',
    'Keep ride': 'Garder le trajet',
    'Cancel ride': 'Annuler le trajet',
    'Ride cancelled.': 'Trajet annulé.',
    'Message': 'Message',
    'Call': 'Appeler',
    'Safety': 'Sécurité',
    'RIMA Driver': 'Chauffeur RIMA',
    'your driver': 'votre chauffeur',
    'Pickup location': 'Point de départ',
    'New driver': 'Nouveau chauffeur',
    'Driver vehicle': 'Véhicule du chauffeur',
    'Check plate': 'Vérifiez la plaque',
    'Ride': 'Trajet',
    'Trip time': 'Durée du trajet',
    'Estimated fare': 'Tarif estimé',
    'RIMA Chat': 'Chat RIMA',
    'Messages are automatically translated to your preferred language when needed.': 'Les messages sont automatiquement traduits dans votre langue préférée si nécessaire.',
    'No messages yet': 'Aucun message pour le moment',
    'Send a message about pickup, landmarks, timing, or the ride.': 'Envoyez un message concernant le départ, un repère, l’heure ou le trajet.',
    'Unable to send message.': 'Impossible d’envoyer le message.',
    'Unable to load messages.': 'Impossible de charger les messages.',
    'Original message': 'Message original',
    'Translation unavailable — showing original message.': 'Traduction indisponible — affichage du message original.',
    'Arabic': 'Arabe',
    'French': 'Français',
    'English': 'Anglais',
    'your language': 'votre langue',
    'Wallet': 'Portefeuille',
    'RIMA Wallet': 'Portefeuille RIMA',
    'Ride payments': 'Paiements des trajets',
    'Your completed and pending ride transactions appear here.': 'Vos paiements de trajets terminés et en attente apparaissent ici.',
    'Transactions': 'Transactions',
    'No transactions yet': 'Aucune transaction pour le moment',
    'Your RIMA ride payments will appear here.': 'Vos paiements de trajets RIMA apparaîtront ici.',
    'Unable to load wallet activity.': 'Impossible de charger l’activité du portefeuille.',
    'Messages': 'Messages',
    'Messages with your driver will appear here.': 'Les messages avec votre chauffeur apparaîtront ici.',
    'RIMA ride': 'Trajet RIMA',
    'No notifications yet.': 'Aucune notification pour le moment.',
  };

  static const Map<String, String> _ar = {
    'RIMA customer': 'عميل RIMA',
    'Profile': 'الملف الشخصي',
    'Personal information': 'المعلومات الشخصية',
    'Saved places': 'الأماكن المحفوظة',
    'Language': 'اللغة',
    'Notifications': 'الإشعارات',
    'Help & support': 'المساعدة والدعم',
    'Logout': 'تسجيل الخروج',
    'Log out': 'تسجيل الخروج',
    'Log out?': 'تسجيل الخروج؟',
    'Are you sure you want to log out?': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'Cancel': 'إلغاء',
    'Personal information updated.': 'تم تحديث المعلومات الشخصية.',
    'First name': 'الاسم الأول',
    'Last name': 'اسم العائلة',
    'Email': 'البريد الإلكتروني',
    'Saving...': 'جارٍ الحفظ...',
    'Save changes': 'حفظ التغييرات',
    'No saved places yet': 'لا توجد أماكن محفوظة بعد',
    'Places saved during booking will appear here.': 'ستظهر هنا الأماكن المحفوظة أثناء الحجز.',
    'Saved place': 'مكان محفوظ',
    'Location': 'الموقع',
    'Push notifications': 'الإشعارات الفورية',
    'Ride updates, driver arrival and important RIMA alerts': 'تحديثات الرحلة ووصول السائق وتنبيهات RIMA المهمة',
    'Your support request was sent.': 'تم إرسال طلب الدعم.',
    'Unable to send support request.': 'تعذر إرسال طلب الدعم.',
    'How can we help?': 'كيف يمكننا مساعدتك؟',
    'Send a message to the RIMA support team.': 'أرسل رسالة إلى فريق دعم RIMA.',
    'Subject': 'الموضوع',
    'Message': 'رسالة',
    'Sending...': 'جارٍ الإرسال...',
    'Send to support': 'إرسال إلى الدعم',
    'Use current location': 'استخدام موقعك الحالي',
    'Getting your location...': 'جارٍ تحديد موقعك...',
    'Location services are disabled': 'خدمات الموقع معطلة',
    'Location permission denied': 'تم رفض إذن الموقع',
    'Location permission permanently denied': 'تم رفض إذن الموقع نهائيًا',
    'Your current location': 'موقعك الحالي',
    'Unable to get location': 'تعذر تحديد موقعك',
    'Pickup confirmed': 'تم تأكيد نقطة الانطلاق',
    'Pickup location confirmed': 'تم تأكيد موقع الانطلاق',
    'Where would you like to go?': 'إلى أين تريد الذهاب؟',
    'Choose your pickup and destination.': 'اختر نقطة الانطلاق والوجهة.',
    'Pickup': 'نقطة الانطلاق',
    'Destination': 'الوجهة',
    'Where are you going?': 'إلى أين تريد الذهاب؟',
    'Your pickup': 'نقطة انطلاقك',
    'Move the map to fine-tune your pickup point.': 'حرّك الخريطة لتحديد نقطة الانطلاق بدقة.',
    'Pickup changed': 'تم تغيير نقطة الانطلاق',
    'Confirm pickup': 'تأكيد نقطة الانطلاق',
    'Quick locations': 'المواقع السريعة',
    'Home': 'المنزل',
    'Work': 'العمل',
    'Saved': 'المحفوظة',
    'Pickup help': 'مساعدة نقطة الانطلاق',
    'Use GPS, move the pin, or choose a nearby landmark.': 'استخدم GPS أو حرّك الدبوس أو اختر معلمًا قريبًا.',
    'Choose destination': 'اختر الوجهة',
    'Move map to adjust pickup': 'حرّك الخريطة لضبط نقطة الانطلاق',
    'Ride history': 'سجل الرحلات',
    'Retry': 'إعادة المحاولة',
    'No ride history yet': 'لا يوجد سجل رحلات بعد',
    'Completed and cancelled rides will appear here.': 'ستظهر هنا الرحلات المكتملة والملغاة.',
    'Unknown date': 'تاريخ غير معروف',
    'Completed': 'مكتملة',
    'Cancelled': 'ملغاة',
    'Ride receipt': 'إيصال الرحلة',
    'Ride completed': 'اكتملت الرحلة',
    'Ride cancelled': 'تم إلغاء الرحلة',
    'Trip': 'الرحلة',
    'Ride ID': 'رقم الرحلة',
    'Date': 'التاريخ',
    'Distance': 'المسافة',
    'Duration': 'المدة',
    'Driver': 'السائق',
    'Customer': 'العميل',
    'Vehicle': 'المركبة',
    'Plate': 'لوحة السيارة',
    'Your rating': 'تقييمك',
    'Rating': 'التقييم',
    'Comment': 'التعليق',
    'Payment': 'الدفع',
    'Status': 'الحالة',
    'Method': 'الطريقة',
    'Amount': 'المبلغ',
    'Transaction': 'المعاملة',
    'Paid': 'مدفوع',
    'Not configured': 'غير مُعد',
    'Not started': 'لم يبدأ',
    'Pending': 'قيد الانتظار',
    'Authorized': 'مصرّح',
    'Processing': 'قيد المعالجة',
    'Failed': 'فشل',
    'Refunded': 'مسترد',
    'Finding your driver': 'جارٍ البحث عن سائق',
    'Driver found': 'تم العثور على سائق',
    'Payment required': 'الدفع مطلوب',
    'Payment confirmed': 'تم تأكيد الدفع',
    'Driver on the way': 'السائق في الطريق',
    'Driver has arrived': 'وصل السائق',
    'Ride in progress': 'الرحلة جارية',
    'Searching for available RIMA drivers nearby.': 'جارٍ البحث عن سائقي RIMA المتاحين بالقرب منك.',
    'A RIMA driver accepted your ride.': 'قبل سائق RIMA رحلتك.',
    'Your driver accepted the ride. Complete payment to confirm your trip.': 'قبل السائق الرحلة. أكمل الدفع لتأكيد الرحلة.',
    'Your payment is confirmed. Your driver can now head to your pickup location.': 'تم تأكيد الدفع. يمكن للسائق الآن التوجه إلى نقطة الانطلاق.',
    'Your driver is heading to your pickup location.': 'السائق في طريقه إلى نقطة الانطلاق.',
    'Your driver is waiting at your pickup location.': 'السائق ينتظرك عند نقطة الانطلاق.',
    'You are on your way to your destination.': 'أنت الآن في طريقك إلى وجهتك.',
    'Thank you for riding with RIMA. Please rate your driver.': 'شكرًا لاستخدام RIMA. يرجى تقييم السائق.',
    'This ride has been cancelled. Returning home...': 'تم إلغاء الرحلة. جارٍ العودة إلى الرئيسية...',
    'Checking your ride status...': 'جارٍ التحقق من حالة الرحلة...',
    'Cancel ride?': 'إلغاء الرحلة؟',
    'Are you sure you want to cancel this RIMA ride?': 'هل أنت متأكد أنك تريد إلغاء رحلة RIMA هذه؟',
    'Keep ride': 'الاحتفاظ بالرحلة',
    'Cancel ride': 'إلغاء الرحلة',
    'Ride cancelled.': 'تم إلغاء الرحلة.',
    'Call': 'اتصال',
    'Safety': 'السلامة',
    'RIMA Driver': 'سائق RIMA',
    'your driver': 'سائقك',
    'Pickup location': 'موقع الانطلاق',
    'New driver': 'سائق جديد',
    'Driver vehicle': 'مركبة السائق',
    'Check plate': 'تحقق من اللوحة',
    'Ride': 'الرحلة',
    'Trip time': 'مدة الرحلة',
    'Estimated fare': 'الأجرة التقديرية',
    'RIMA Chat': 'محادثة RIMA',
    'Messages are automatically translated to your preferred language when needed.': 'تتم ترجمة الرسائل تلقائيًا إلى لغتك المفضلة عند الحاجة.',
    'No messages yet': 'لا توجد رسائل بعد',
    'Send a message about pickup, landmarks, timing, or the ride.': 'أرسل رسالة عن نقطة الانطلاق أو المعالم أو التوقيت أو الرحلة.',
    'Unable to send message.': 'تعذر إرسال الرسالة.',
    'Unable to load messages.': 'تعذر تحميل الرسائل.',
    'Original message': 'الرسالة الأصلية',
    'Translation unavailable — showing original message.': 'الترجمة غير متاحة — يتم عرض الرسالة الأصلية.',
    'Arabic': 'العربية',
    'French': 'الفرنسية',
    'English': 'الإنجليزية',
    'your language': 'لغتك',
    'Wallet': 'المحفظة',
    'RIMA Wallet': 'محفظة RIMA',
    'Ride payments': 'مدفوعات الرحلات',
    'Your completed and pending ride transactions appear here.': 'تظهر هنا معاملات الرحلات المكتملة وقيد الانتظار.',
    'Transactions': 'المعاملات',
    'No transactions yet': 'لا توجد معاملات بعد',
    'Your RIMA ride payments will appear here.': 'ستظهر هنا مدفوعات رحلات RIMA.',
    'Unable to load wallet activity.': 'تعذر تحميل نشاط المحفظة.',
    'Messages': 'الرسائل',
    'Messages with your driver will appear here.': 'ستظهر هنا رسائلك مع السائق.',
    'RIMA ride': 'رحلة RIMA',
    'No notifications yet.': 'لا توجد إشعارات بعد.',
  };

  static String get(String key) {
    final code = RimaLocaleController.code;
    return _values[code]?[key] ?? _values['en']?[key] ?? key;
  }

  static String ui(String english) {
    switch (RimaLocaleController.code) {
      case 'fr':
        return _fr[english] ?? english;
      case 'ar':
        return _ar[english] ?? english;
      default:
        return english;
    }
  }
}
